### ISSUE TITLE
Etoro trading API

### ISSUE THREAD

**Issue by Pozo** [oleh2208/etoro-trading-api#1]
As far as I know there is a trading API for Etoro, you just have to sign up to api-portal.etoro.com and subscribe for it.

**Comment by oleh2208** [comment]
Hi,
thanks for information, but it seems
 those API are  not availible, still in development.

________________________________
От: Zoltan Polgar <notifications@github.com>
Отправлено: 18 декабря 2018 г. 15:39
Кому: oleh2208/etoro-trading-api
Копия: Subscribed
Тема: [oleh2208/etoro-trading-api] Etoro trading API (#1)


As far as I know there is a trading API for Etoro, you just have to sign up to api-portal.etoro.com and subscribe for it.

**Comment by Pozo** [comment]
Yeah, it seems it's not working in production environment. I just checked yesterday the comments on that site and it seems that's a dead project. 

Cheers, Zoltan
